[package]
name = "tcx-fuzz-target"
version = "0.1.0"
authors = ["Neal Xu <imxuneal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0.4"
url = "1.0"
tcx = { path = "./tcx" }

[workspace]
