[package]
name = "tcx-primitive"
version = "0.1.0"
authors = ["tyrone <2125081@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.18.0"
byteorder = "1.2"
secp256k1 = "0.12"
hex-literal = "0.2"
hex = "0.3.2"
lazy_static = "1.3.0"
